config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  post '/upload', to: 'search_results#upload'
  get '/raw_code/:id', to: 'search_results#raw_code', as: 'raw_code'
  delete '/destroy/:id', to: 'search_results#destroy', as: 'destroy_search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :user

  validates :links_count, numericality: { only_integer: true }
  validates :adwords_count, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :search_results, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery except: :index
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search_result = SearchResult.new
    @searches = current_user.search_results if current_user
  end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  before_action :extract_data, only: :upload
  before_action :load_search, only: [:raw_code, :destroy]

  def upload(data)
    #
    # converting data to array, nested arrays to single array
    #
    queries = data.to_a.flatten.compact

    unless queries.empty? || queries.count > 100
      #
      # send the data to redis server so sidekiq will load from there and save queries to database
      #
      UploadDataJob.perform_later(queries, current_user)
    else
      flash[:errors] = 'Search Queries in the file are either more than 100 or empty'
    end

    redirect_to :root
  end

  def raw_code
    @raw_data = @search.html_code
  end

  def destroy
    @search.destroy

    redirect_to :root
  end


  private

  def extract_data
    if params[:search_result]
      file = params[:search_result][:file]

      begin
        data = CSV.read((file.path))

        upload(data)
      rescue
        flash[:errors] = 'Unsupported file type! Only CSV type supported!'
        redirect_to :root
      end
    else
      flash[:errors] = 'Please Upload a File'
      redirect_to :root
    end
  end

  def load_search
    @search = SearchResult.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 id="heading"> User Queries </h1>

<% if user_signed_in? %>

  <p class="errors"><%= flash[:errors] %></p>

  <div id="file-upload" >
    <%= form_for @search_result , url: { controller: 'search_results', action: 'upload', method: :post } do | f | %>

      <p>Upload CSV File</p>

      <label><%= f.file_field :file, accept: 'text/csv' %></label>

      <%= f.submit 'Upload', data: {disable_with: "Analyzing..."}, class: 'btn btn-success' %>

    <% end %>
  </div>

  <div id="results">
  <% if @searches.any? %>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Keywords</th>
          <th>Duration</th>
          <th>#Links</th>
          <th>#GAds</th>
          <th>Raw file</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% i = 1 %>
        <% @searches.each do | search | %>
          <tr class="trow-light">
            <td><%= i %></td>
            <td><%= search.keyword %></td>
            <td><%= search.results_count %></td>
            <td><%= search.links_count %></td>
            <td><%= search.adwords_count %></td>
            <td><%= link_to 'View', raw_code_path(search.id), target: '_blank', class: "view" %></td>
            <td><%= link_to 'Delete', destroy_search_path(search.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "delete" %></td>
          </tr>
          <% i += 1 %>
        <% end %>
      </tbody>
    </table>

  <% end %>

  </div>

  <div id="log-out">
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"btn btn-warning" %>
  </div>

<% else %>

  <p class='info'>Login/Signup to upload a CSV file of list of queries to search on google.</p>

  <div id="session-buttons">
  <button type="button" class="btn btn-primary"><%= link_to 'Sign In', new_user_session_path, class: :user_session %></button>

  <button type="button" class="btn btn-primary"><%= link_to 'Sign Up', new_user_registration_path, class: :user_session  %></button>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Queries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search_results/raw_code.html.erb
<%= @raw_data %>